# Generated by Django 4.1.4 on 2022-12-28 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='publisher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.publisher'),
        ),
    ]
