# Generated by Django 4.1.4 on 2022-12-30 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_developer_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.publisher'),
        ),
    ]
