# Generated by Django 4.1.4 on 2023-01-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_location_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='country',
        ),
    ]
