# Generated by Django 4.1.4 on 2023-01-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_location_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='image',
        ),
    ]
